data_project:
  outputs:
    dev:
      dataset: "{{ env_var('DBT_GOOGLE_BIGQUERY_DATASET') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('DBT_GOOGLE_BIGQUERY_KEYFILE') }}"
      location: "{{ env_var('DBT_GOOGLE_BIGQUERY_LOCATION') }}"
      method: service-account
      project: "{{ env_var('DBT_GOOGLE_PROJECT') }}"
      priority: interactive
      threads: 4
      type: bigquery
  target: dev
